language: python
python:
  - 2.7

cache:
    - apt
    - pip

sudo: required

# Setup anaconda
before_install:
  - sudo apt-get update -q
  - sudo apt-get install python-gobject-2 -y
  - sudo apt-get install python-gtk2 -y
  - sudo apt-get install python-lxml -y
  - sudo apt-get install python-pygoocanvas -y
  - sudo apt-get install python-kiwi -y
install:
  #- pip install lxml
  - pip install python-ase
  - pip install kiwi-gtk
  - pip show kiwi-gtk
  - wget http://http.us.debian.org/debian/pool/main/g/gazpacho/gazpacho_0.7.2-3_all.deb
  - sudo dpkg -i gazpacho_0.7.2-3_all.deb
  - python setup.py install #install kmos
 
script:
    - dpkg-query -L python-kiwi
    - export PYTHONPATH=/usr/share/pyshared/:${PYTHONPATH}
    - export PYTHONPATH=/usr/lib/python2.7/dist-packages/:${PYTHONPATH}
    - python -c "import sys; import pprint; pprint.pprint(sys.path)"
    - python -c 'import pprint; import kiwi.ui.gazpacholoader; pprint.pprint(dir(kiwi.ui.gazpacholoader))'
    - nosetests
