language: python
python:
  - 2.7

cache:
    - apt
    - pip

# Setup anaconda
before_install:
  ## install numpy python environment
  #- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  #- chmod +x miniconda.sh
  #- ./miniconda.sh -b
  #- export PATH=/home/travis/miniconda2/bin:$PATH
  #- conda update --yes conda
  #- conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  #- conda install --yes -n condaenv pip
  #- source activate condaenv
  - sudo apt-get update -q
  - sudo apt-get install python-gobject-2 -y
  - sudo apt-get install python-gtk2 -y
  ## PyGobject
  #- wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
  #- tar xf pygobject-2.28.6.tar.bz2
  #- cd pygobject-2.28.6
  #- ./configure --prefix=$VIRT_ROOT --disable-introspection > /dev/null
  #- make > /dev/null
  #- make install > /dev/null
  #- cd ..
  ## install pygtk 
  #- wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  #- tar xf pygtk-2.24.0.tar.bz2
  #- cd pygtk-2.24.0
  #- export PKG_CONFIG_PATH=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/pkgconfig
  #- ./configure --prefix=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/
  #- make
  #- make install
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
# Install packages

install:
  #- conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose
  #- pip install mpmath
  - pip install lxml
  - pip install python-ase
  - python setup.py install #install kmos
 
script:
    - nosetests
