language: python
python:
  - 2.7

cache:
    - apt
    - pip

sudo: required

# Setup anaconda
before_install:
  ## install numpy python environment
  #- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  #- chmod +x miniconda.sh
  #- ./miniconda.sh -b
  #- export PATH=/home/travis/miniconda2/bin:$PATH
  #- conda update --yes conda
  #- conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  #- conda install --yes -n condaenv pip
  #- source activate condaenv
  - sudo apt-get update -q
  - sudo apt-get install python-gobject-2 -y
  - sudo apt-get install python-gtk2 -y
  - sudo apt-get install python-lxml -y
  - sudo apt-get install python-pygoocanvas -y
  #- sudo apt-get install python-kiwi -y
  - wget http://http.us.debian.org/debian/pool/main/g/gazpacho/gazpacho_0.7.2-3_all.deb
  - sudo dpkg -i gazpacho_0.7.2-3_all.deb
  ## PyGobject
  #- wget http://ftp.gnome.org/pub/GNOME/sources/pygobject/2.28/pygobject-2.28.6.tar.bz2
  #- tar xf pygobject-2.28.6.tar.bz2
  #- cd pygobject-2.28.6
  #- ./configure --prefix=$VIRT_ROOT --disable-introspection > /dev/null
  #- make > /dev/null
  #- make install > /dev/null
  #- cd ..
  ## install pygtk 
  #- wget http://ftp.gnome.org/pub/GNOME/sources/pygtk/2.24/pygtk-2.24.0.tar.bz2
  #- tar xf pygtk-2.24.0.tar.bz2
  #- cd pygtk-2.24.0
  #- export PKG_CONFIG_PATH=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/pkgconfig
  #- ./configure --prefix=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION/
  #- make
  #- make install
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm
# Install packages

install:
  #- pip install lxml
  - pip install python-ase
  - pip install kiwi-gtk
  - python setup.py install #install kmos
 
script:
    - dpkg-query -L python-kiwi
    - export PYTHONPATH=/usr/share/pyshared/:${PYTHONPATH}
    - export PYTHONPATH=/usr/lib/python2.7/dist-packages/:${PYTHONPATH}
    - python -c "import sys; import pprint; pprint.pprint(sys.path)"
    - python -c 'import pprint; import kiwi.ui.gazpacholoader; pprint.pprint(dir(kiwi.ui.gazpacholoader))'
    - nosetests
